apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "sentry-kubernetes.labels" . | indent 4 }}
  name: {{ template "sentry-kubernetes.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "sentry-kubernetes.name" . }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry-kubernetes.name" . }}
        release: {{.Release.Name }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      {{- if .Values.customCA }}
      volumes:
        - name: custom-ca
          secret:
            secretName: {{ .Values.customCA.secretName | quote }}
        - name: cacert
          emptyDir: {}
      initContainers:
      - name: ca-bundle-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: custom-ca
            mountPath: /etc/pki/ca-trust/custom/ca.crt
            subPath: {{ .Values.customCA.item | quote }}
          - name: cacert
            mountPath: /tmp/cacert
        command:
          - /bin/bash
          - -c
          - cat /usr/local/lib/python3.7/site-packages/certifi/cacert.pem /etc/pki/ca-trust/custom/ca.crt > /tmp/cacert/cacert.pem
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: {{ template "sentry-kubernetes.secretName" . }}
                key: sentry.dsn
          {{ if .Values.sentry.environment }}
          - name: ENVIRONMENT
            value: {{ .Values.sentry.environment }}
          {{ end }}
          {{ if .Values.sentry.release }}
          - name: RELEASE
            value: {{ .Values.sentry.release }}
          {{ end }}
          {{ if .Values.sentry.logLevel }}
          - name: LOG_LEVEL
            value: {{ .Values.sentry.logLevel }}
          {{ end }}
          {{ if .Values.customCA }}
          - name: REQUESTS_CA_BUNDLE
            value: /etc/pki/ca-trust/custom/ca.crt
          {{ end }}
        {{- if .Values.customCA }}
        volumeMounts:
          - name: custom-ca
            mountPath: /etc/pki/ca-trust/custom/ca.crt
            subPath: {{ .Values.customCA.item | quote }}
            readOnly: true
          - name: cacert
            mountPath: /usr/local/lib/python3.7/site-packages/certifi/cacert.pem
            subPath: cacert.pem
            readOnly: true
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      serviceAccountName: {{ template "sentry-kubernetes.serviceAccountName" . }}
